### ISSUE TITLE
Feature Request: Labels

### ISSUE THREAD

**Issue by Josh-Dovey** [TimBaumgart/flutter_map_polywidget#3]
Hi,
I need to add a label (that is wider than the PolyWidget) above the PolyWidget.

My PolyWidgets are 5x5 meters wide. If I add a Text widget within the PolyWidget, the Text will wrap until the map's zoom level is greater than 20.

That attached images will help visualise what I am trying to do:
![code](https://github.com/TimBaumgart/flutter_map_polywidget/assets/69112686/177d859a-9d08-4736-8d60-8400b8ac24bc)
![Screenshot 2023-10-10 at 12 08 21](https://github.com/TimBaumgart/flutter_map_polywidget/assets/69112686/19a4970a-77a7-45d9-9136-bacbdc50e02c)

New label and labelPosition parameters would be a great feature for this flutter_map plugin. Do you intend to add a feature like this into flutter_map_polywidget or do you know an implementation I could use on top of the existing plugin?

Thanks in advance

**Comment by TimBaumgart** [comment]
Hi,

depending on what your results should look like, I can think of three solutions:
1. add minimum constraints to your polywidget (like this: https://pub.dev/packages/flutter_map_polywidget#constraints). This will shrink your label when the polywidget is too small due to the current zoom. You need at least v0.1.0 to use constraints.
2. use a badge (https://api.flutter.dev/flutter/material/Badge-class.html) to display your label. Badges are placed outside of the scope of flutter_map, so they will stay the same size.
3. expand your polywidget (e.g. 10x10 meters) and use FractionallySizedBox to shrink your child back to 5x5 meters. outside your 5x5 box you can display whatever you want now. I am considering to add this functionality to the polywidget package, but for now you have to code it yourself.

Does any of these solutions work for you?

**Comment by Josh-Dovey** [comment]
Thanks for your suggestions! 

The second option you gave of using a badge has worked well. I can use the 'isLabelVisible' property to hide the Badge until I reach a specific zoom level.
